[package]
name = "src-back"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
crossbeam-utils = "0.8.20"
hyper = { version = "1.4.1", features = ["full"] }
once_cell = "1.19.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
tower = "0.4.13"
