[package]
name = "partyback"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
axum-valid = "0.19.0"
axum_session_auth = "0.14.0"
crossbeam-utils = "0.8.20"
hyper = { version = "1.4.1", features = ["full"] }
sea-orm = { version = "1.0.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-json", "with-uuid", "with-time", "with-rust_decimal" ] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
tower = "0.4.13"
tower-sessions = "0.12.3"
