[package]
name = "partyback"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
axum-valid = "0.19.0"
crossbeam-utils = "0.8.20"
fred = "9.1.2"
hyper = { version = "1.4.1", features = ["full"] }
nuid = "0.5.0"
sea-orm = { version = "1.0.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-json", "with-uuid", "with-time", "with-rust_decimal" ] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
short-uuid = "0.1.3"
sqids = "0.4.1"
tokio = { version = "1.38.1", features = ["full"] }
tower = "0.4.13"
tower-sessions = "0.12.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
yb-tokio-postgres = "0.7.10-yb-1-beta.1"
