stages:
  - build
  - deploy

# Job for building the front-end
build_frontend:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .output/public/

# Job for building the back-end
build_backend:
  stage: build
  image: rust:latest
  script:
    - cd src-back
    - cargo build --release
  artifacts:
    paths:
      - src-back/target/release/

# Job for deploying the front-end to Nginx
# deploy_frontend:
#   stage: deploy
#   script:
#     - rm -rf /var/www/partyfront/*
#     - cp -rf .output/public /var/www/partyfront/
#     - rm -rf /var/cache/nginx/ramcache/*
#   after_script:
#     - nginx -s reload
#   only:
#     - main

# Job for deploying the back-end to Nginx reverse proxy
# deploy_backend:
#   stage: deploy
#   script:
#     - rm -f /usr/bin/partyback
#     - cp -f src-back/target/release/partyback /usr/bin/partyback
#   after_script:
#     - systemctl restart partyback
#   only:
#     - main
