name: CI/CD Pipeline

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != '[skip]'
    environment:
      name: Production
      url: 'https://partycal.site/'

    steps:
    - uses: actions/checkout@v4.1.7
    - run: corepack enable
    - name: DB compile check
      uses: selfagency/ssh-port-forward-action@v1.0.6
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        ssh-host: ${{ secrets.SSH_IP }}
        ssh-port: ${{ secrets.SSH_PORT }}
        ssh-user: ${{ secrets.SSH_USER_DEFAULT }}
        local-port: ${{ secrets.DB_PORT }}
        remote-host: localhost
        remote-port: ${{ secrets.DB_PORT }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      with:
        target: 'x86_64-unknown-linux-gnu'
        cache-workspaces: 'src-back -> target'
        rustflags: ''

    - name: Build Front-end
      run: |
        pnpm install
        pnpm run build

    - name: Build Back-end
      run: |
        cargo build --release
      working-directory: ./src-back

    - name: Package Release Files
      run: |
        mkdir -p release/partycal
        cp -rf .output/public/* release/partycal
        cp -f src-back/target/release/partyback release/partycal/partyback
        cd release
        tar -zcvf partycal.tar.gz partycal

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_IP }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SOURCE: "release/partycal.tar.gz"
        TARGET: "/opt/partycal.tar.gz"
        SCRIPT_BEFORE: |
          systemctl stop partyback
          rm -rf /opt/ramdisk/*
          rm -rf /opt/partycal/*
          rm -f /opt/partyback
        SCRIPT_AFTER: |
          tar -zxvf /opt/partycal.tar.gz -C /opt
          mv /opt/partycal/partyback /opt/partyback
          rm -f /opt/partycal.tar.gz
          chown -R ${{ secrets.SSH_USER_DEFAULT }}:${{ secrets.SSH_USER_DEFAULT }} /opt/partycal
          chmod -R 755 /opt/partycal
          chown ${{ secrets.SSH_USER_DEFAULT }}:${{ secrets.SSH_USER_DEFAULT }} /opt/partyback
          chmod 755 /opt/partyback
          nginx -s reload
          systemctl start partyback
    
          
